language: node_js
node_js:
  - "8"
  - "stable"
dist: trusty
sudo: true

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - ng test --watch false -cc
  - ng build
  - ng e2e

