language: node_js
node_js:
  - "6"
  - "8"

sudo: enabled

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run test:headless
  - npm run build
  - xvfb-run npm run e2e
